### ISSUE TITLE
is there an objective-c version as swift files are much bigger when compiled 

### ISSUE THREAD

**Issue by markmark1** [fortmarek/SwipeViewController#20]
as swift files are much bigger

**Comment by fortmarek** [comment]
Unfortunately, there is not - the project is based on Objective-C project, you can find it here: https://github.com/cwRichardKim/RKSwipeBetweenViewControllers 
It is not exactly the same since I have made some more or less minor changes to it but you can give it a shot. (closing for now, but do not hesitate to ask any other questions ✌)
